### PR TITLE
feat: allow user to specify and override thumb and thumbInner styles or provide their own custom thumb component

### PR DESCRIPTION
**Pull request by adamhari**
Introduces two new props to `ColorPicker`, `Panel` and `Slider` components: `thumbStyle` and `thumbInnerStyle`.

Particularly useful for overriding the default shadow styling.

### CODE REVIEW

**Comment by alabsi91** [comment]
I was planning to do this implementation earlier, but it has some drawbacks. For instance, if the user overrides the `thumbSize` prop, it can break things because the calculation relies on it. Additionally, placing the `thumbStyle` inside `useAnimatedStyle` might affect performance, but I am not entirely sure about that. I have some ideas that we could discuss: 

- One is to remove the `thumbStyle` and `thumbInnerStyle` props and allow the user to provide a custom thumb component with its props passed to it.
-  Another idea is to define the style properties that the user can change and move `thumbStyle` outside of `useAnimatedStyle`.

**Comment by alabsi91** [comment]
I think the user should be responsible for handling the component, and we can provide examples in the documentation. In my opinion, custom thumbs are for advanced users, and most users won't use them, so it's appropriate to let the user handle everything.

**Comment by alabsi91** [comment]
I suggest implementing a global property, as well as individual properties for each slider, in the simplest way possible.

**Comment by alabsi91** [comment]
I'm currently working on an `InputWidget` component. I hope you'll take a look at it when it's convenient for you in https://github.com/alabsi91/reanimated-color-picker/pull/11

image

**Comment by adamhari** [comment]
> I'm currently working on an `InputWidget` component. I hope you'll take a look at it when it's convenient for you in #11
> 
> image

For sure, I'm interested in using this feature for my project.

**Comment by adamhari** [comment]
Hey this is ready for another review. I'm having troubles building the docs to preview them locally so the `renderThumb` example might look bad. I felt it was necessary to include it so it's clear that an `Animated` component and `handleStyle` are necessary to make it work like the built-in thumbs.

image

**Comment by alabsi91** [comment]
> Hey this is ready for another review. I'm having trouble building the docs to preview them locally so the `renderThumb` example might look bad. I felt it was necessary to include it so it's clear that an `Animated` component and `handleStyle` are necessary to make it work like the built-in thumbs.
> 
> image

- Check out the [docusaurus website](https://docusaurus.io/) it might help with the preview issue.

**Comment by adamhari** [comment]
Does it work for you by calling `npm run buld` from the `docusaurus` dir? I get this error when I use the config as-is, I tried changing the `baseUrl` with no success.

image

**Comment by alabsi91** [comment]
> Does it work for you by calling `npm run buld` from the `docusaurus` dir? I get this error when I use the config as-is, I tried changing the `baseUrl` with no success.
> 
> image

- Check out the command `npm run start`; it will start a local server.

**Comment by adamhari** [comment]
Thanks, it worked. Docs look ok to me.

**Comment by alabsi91** [comment]
If you have spotted a typo or a grammar mistake while reviewing the documentation website, please consider correcting it. 🙏

**Comment by alabsi91** [comment]
Is it ok to merge now ?

**Comment by adamhari** [comment]
Yeah

**Pull request merged**
