### PR TITLE
use 0 duration animation for initial setColor timings

### PR DESCRIPTION
**Pull request by adamhari**
fixes https://github.com/alabsi91/reanimated-color-picker/issues/4

### CODE REVIEW

**Comment by alabsi91** [comment]
This is great 👍, but I tried to eliminate the animation at initial mount. However, I encountered a problem on slower phones: the slider's thumb does not move to its proper place on the first mount. Therefore, I reversed my changes. Perhaps we could add a prop to disable the initial animation? What do you think?

**Comment by adamhari** [comment]
I like the idea of making this configurable. I have a couple of thoughts:
- instead of setting the duration to `0` for the first `setColor` call, could we instead parse the value prop prior to assigning the initial shared values? This might solve for the slow phone issue
- could we consider making the prop disable the color change animation altogether? It looks ok for most of the UIs but, for `Panel3` in particular, the color interpolation causes the x and y positions to curve towards it's end position which looks odd even after the initial render

**Comment by alabsi91** [comment]
Yes, I like your solution. The issue was with `useDerivedValue` not triggering on the first attempt for older phones. That's why I kept the animation on the first mount.

The initial animation should be disabled by default, as I don't think anyone wants it. However, we could provide a `duration` prop. What are your thoughts?"

**Comment by adamhari** [comment]
Sounds good to me, I adjusted the PR.

**Pull request merged**
