### PR TITLE
set hsva values in onStart

### PR DESCRIPTION
**Pull request by adamhari**
This PR refactors the color logic out of `onActive` so it can also be applied in `onStart`. As a result, Android and iOS thumbs can have their position updated by tapping instead of having to tap and then drag before the values update.

https://user-images.githubusercontent.com/16565387/222799629-3c7255ac-893e-4cba-97dd-6f66caa5e049.mov

### CODE REVIEW

**Comment by alabsi91** [comment]
How about using a `worklet` function for the `setValueFromGestureEvent` function to eliminate the need for `runOnJs`? Do you think that's possible?

**Comment by adamhari** [comment]
Updated the PR. Would you consider adding a prettier config or something similar to the repo to make formatting PRs easier?

**Comment by alabsi91** [comment]
Yes, sure. I didn't add it because I'm currently using a global config. 🙂

**Comment by alabsi91** [comment]
Tapping on the slider won't trigger the `onChange` event, right?

**Comment by adamhari** [comment]
On native the `onActive` callback only fires after you've dragged a small distance after tapping. On web with `enableExperimentalWebImplementation=true` `onActive` is the only event that fires, including when you tap on the slider.

**Comment by adamhari** [comment]
I suppose we need to call `onGestureChange` from `onStart` as well?

**Comment by alabsi91** [comment]
If the user taps on the slider in the native app, will the `onChange` event not be triggered? Is there a way to fix that?

**Comment by adamhari** [comment]
Tested with external state that syncs via `onChange` to confirm that it now fires when tapping on native.

**Comment by alabsi91** [comment]
Ready to merge?

**Comment by adamhari** [comment]
Yeah it's ready now.

**Pull request merged**
