### PR TITLE
Feature: Integrate Custom Gestures in Color Picker Components

### PR DESCRIPTION
**Pull request by alabsi91**
## Description:
This pull request introduces a new feature to the color picker components by adding a `gestures` prop.
This prop accepts an array of React Native Gesture Handler gestures, allowing custom gestures or composed ones to run with the existing color picker gestures.

### CODE REVIEW

**Comment by MehediH** [comment]
This is good stuff, thanks @alabsi91! However, I think there needs to be some changes here. First, let me explain the use case again:

```tsx
<ColorPicker>
  <GestureDetector gesture={longPressGesture}>
      <Swatches style={{ paddingTop: 10, paddingHorizontal: 10 }} />
  </GestureDetector>

  <Panel4
        style={[panelStyle, { borderRadius: 0 }]}
        gestures={[longPressGesture]}
      />
</ColorPicker>
```

Basically: when we have a `longPress` on the `<Swatches/>`, we want to show the `<Panel4/>` and also simultaneously allow the gestures in `Panel4`. 

This will likely require a lot more work. I am thinking maybe a `gestures` prop in the `<ColorPicker/>` wrapper, that gets passed to all the child components like `<Swatches/>`? 

Something like:

```tsx
<ColorPicker gestures={[longPressGesture]}>
  // swatches will have the longPress gesture
  <Swatches style={{ paddingTop: 10, paddingHorizontal: 10 }} />

  // and a wait to override the shared gestures in the component-level too
  // so Panel4 won't have the longPress
  <Panel4 gestures=[]/>
</ColorPicker>
```

what do you think?

**Comment by alabsi91** [comment]
Thank you for testing it so quickly. Each component, including sliders and panels, has its own `GestureDetector`. The Swatches component currently uses `Pressable` for each swatch. Perhaps we could consider using `GestureDetector` for it as well, but I'm uncertain whether to wrap all the swatches together or each one individually. Although making gestures props on the wrapper is a good idea, it seems quite similar to passing them to the slider.

If you have a repository example illustrating what you are attempting to implement, sharing it would be greatly appreciated. This way, I can test different approaches.

**Comment by MehediH** [comment]
@alabsi91 Sure, I don't have an example repo but this is the full component: https://gist.github.com/MehediH/f9d6bd9499bd90ec46dc46777f74ca83 

You should be able to drop it into any sample app. 

> Perhaps we could consider using GestureDetector for it as well, but I'm uncertain whether to wrap all the swatches together or each one individually. 

I think it makes sense to wrap all swatches, to begin with. If there's a use case in the future to allow individual gestures on each swatch, then you could look into that.

Lmk if I can help!

**Comment by alabsi91** [comment]
Thank you for the code; it helped a lot. I played around with it to make it work, and here's what I've learned:

- Gestures should be inside the Panel view to be activated.
- If the panel or its parent has an opacity of 0 or a height of 0, basically when not visible, the gesture won't activate, at least on Android.
- Changing some Panel styles that can directly affect the layout will trigger onLayout inside the Panel.

I couldn't make it work; maybe I will play with it later.

**Comment by MehediH** [comment]
Thank you! I will investigate and lyk if i can fix.

**Pull request merged**
