### PR TITLE
♻️ use runOnUI for onComplete & onChange

### PR DESCRIPTION
**Pull request by VNDRN**
Hi, 
First of all, this lib seems great! One issue we had was that an expensive onComplete function will put a delay on the change of the thumb color like this: 

https://github.com/alabsi91/reanimated-color-picker/assets/60874935/7f4c5ba0-c1e2-4fed-9cab-8c7978816bf2

I've added runOnUI to these functions which gives us the right result: 

https://github.com/alabsi91/reanimated-color-picker/assets/60874935/f27f3b9f-6b63-4101-bf1c-3a8820e91480

Please let me know what you think!

### CODE REVIEW

**Comment by VNDRN** [comment]
I also tested the example app & everything still works!

**Comment by alabsi91** [comment]
Hey @inthepocket, have you tested the app in production mode? This could potentially solve the delay issue. Your changes seem valid to me, but I'm not sure if they might cause any problems for other users' use cases. Additionally, did you try using `runOnUI` in the `onComplete` callback? Do you think this approach would work? Let me know what you think.

**Comment by VNDRN** [comment]
Hi, I ran into some other issues that weren't fixed by this. I've used `thumbShape="solid" `& `thumbColor` to fix this. Will close this PR.

**Comment by alabsi91** [comment]
I'm sorry to hear that. Please feel free to share any problem, and I'll help if I can.

**Pull request closed without merging**
