### PR TITLE
Enable ref in Panel3 to support external gestures simultaneously.

### PR DESCRIPTION
**Pull request by mukesh-simform**
- Panel3 is not working properly with the scroll view, to manage this, we need to manage external gestures simultaneously. As of now, Panel3 doesn't support a ref so I enabled a ref in Panel3

### CODE REVIEW

**Comment by MehediH** [comment]
it would be really helpful to have this for Panel2 or the HueSlider as well

**Comment by alabsi91** [comment]
Can you please try using the `ScrollView` from the Gesture Handler library instead of React Native, and let me know if it solves the issue?
```js
import { ScrollView } from 'react-native-gesture-handler'; 
```

**Comment by MehediH** [comment]
@alabsi91 unfortunately it's not just about the `ScrollView`, I want to be able to combine gestures from a different component with the gestures of the Panels / Sliders but unfortunately this is not possible as the gestures from the main component can't get combined with the Panel gestures. 

@mukesh-simform's fix implements this for Panel3 but would be good to have it for other panels too. thank you for this library!

**Comment by alabsi91** [comment]
Hey @MehediH, thank you for clarifying. I would like to hear from you about use cases other than fixing the ScrollView to get an idea of the best way to expose the gestures API. Is `simultaneousWithExternalGesture(otherGesture1, otherGesture2, ...)` good enough, or should there be the ability to pass a composed gesture? I appreciate your suggestion, and I will add it in the near future.

**Comment by MehediH** [comment]
@alabsi91 simultaneous external gestures should be good enough. But composed gestures will be better. 

I'm basically trying to recreate the color picker on Instagram where you have the swatches and a long tap gesture shows the full color panel: 
https://github.com/alabsi91/reanimated-color-picker/assets/10274434/fac54d17-2d8b-4e66-a9be-e8b3567ceb43

But because there's no way for me to combine the long tap gesture with the gestures inside the Panel, this is not smooth right now. Hope that helps!

**Comment by alabsi91** [comment]
This is easy to implement and appears clean. The concept is that you can provide an array of gestures or composed gestures as a prop for each slider or panel, which will run simultaneously with their respective gestures. The question is whether this approach is useful or if we can enhance it further.
```ts
const composed = Gesture.Simultaneous(
    Gesture.Exclusive(pan, tap, longPress), // gestures for the color picker
    ...extraGestures // It can be an array of gestures or composed gestures
);
```

**Comment by MehediH** [comment]
I think that works well for now!

**Comment by alabsi91** [comment]
I am closing this pull request as I have opened a new one that includes the implementation of the `gestures` prop #59 .

I have published the latest changes to npm for testing purposes. To test the updates, simply run the following command:

```bash
npm i reanimated-color-picker@next
```

**Pull request closed without merging**
